"""add_start_value_to_goals

Revision ID: 6593ce0a7822
Revises: 852ff4380111
Create Date: 2026-04-04 15:49:28.644736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6593ce0a7822'
down_revision: Union[str, Sequence[str], None] = '852ff4380111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('start_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'start_value')
    # ### end Alembic commands ###
