"""add entity_mentions table

Revision ID: 7e8d28a29697
Revises: b4e7a1c9d302
Create Date: 2026-04-06 18:32:31.391825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8d28a29697'
down_revision: Union[str, Sequence[str], None] = 'b4e7a1c9d302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_mentions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('journal_id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('display_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('journal_id', 'entity_type', 'entity_id', name='uq_mention_journal_entity')
    )
    op.create_index('ix_entity_mentions_entity', 'entity_mentions', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_entity_mentions_journal_id', 'entity_mentions', ['journal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_mentions_journal_id', table_name='entity_mentions')
    op.drop_index('ix_entity_mentions_entity', table_name='entity_mentions')
    op.drop_table('entity_mentions')
    # ### end Alembic commands ###
