"""add_lower_is_better_to_goals

Revision ID: 852ff4380111
Revises: 3578b2f8ae58
Create Date: 2026-04-04 15:42:20.126342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852ff4380111'
down_revision: Union[str, Sequence[str], None] = '3578b2f8ae58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('lower_is_better', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'lower_is_better')
    # ### end Alembic commands ###
